spring:
  application:
    name: gulimall-gateway
  cloud:
    nacos:
      discovery:
       server-addr: localhost:8848
    gateway:
      routes:
          - id: ware_route
            uri: lb://gulimall-ware
            predicates:
              - Path=/api/ware/**
            filters:
              - RewritePath=/api/(?<segment>.*),/$\{segment}

          - id: member_route
            uri: lb://gulimall-member
            predicates:
              - Path=/api/member/**
            filters:
              - RewritePath=/api/(?<segment>.*),/$\{segment}

          - id: product_route
            uri: lb://gulimall-product
            predicates:
              - Path=/api/product/**
            filters:
              - RewritePath=/api/(?<segment>.*),/$\{segment}

          - id: third-party_route
            uri: lb://gulimall-third-party
            predicates:
              - Path=/api/third-party/**
            filters:
              - RewritePath=/api/third-party/(?<segment>.*),/$\{segment}

          - id: admin_route
            uri: lb://renren-fast
            predicates:
              - Path=/api/**
            filters:
              - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

          - id: gulimall_search_route
            uri: lb://gulimall-search
            predicates:
              - Host=search.gulimall.com

          - id: gulimall_auth_route
            uri: lb://gulimall-auth-server
            predicates:
              - Host=auth.gulimall.com

          - id: gulimall_cart_route
            uri: lb://gulimall-cart
            predicates:
              - Host=cart.gulimall.com

          - id: gulimall_host_route
            uri: lb://gulimall-product
            predicates:
              - Host=gulimall.com,item.gulimall.com
server:
  port: 9527
