server:
  port: 40000

spring:
  application:
    name: gulimall-cart
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  redis:
    port: 6379
    host: 192.168.92.129

##开启feign对sentinel的支持
#feign:
#  sentinel:
#    enabled: true
#  session:
#    store-type: redis

#配置线程池
gulimall:
  thread:
    coreSize: 20
    maxSize: 200
    keepAliveTime: 10
#
##暴露所有端点
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'


